# This anchor ensures that docker logs never get too fat ;-)
x-logging: &default-logging
  driver: local
  options:
    max-size: "10m"
    max-file: "3"

services:
  swag:
    image: linuxserver/swag:latest
    container_name: ${COMPOSE_PROJECT_NAME}_swag
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      URL: ${SWAG_URL}
      SUBDOMAINS: ${SWAG_SUBDOMAINS}
      VALIDATION: ${SWAG_VALIDATION}
      ONLY_SUBDOMAINS: ${SWAG_ONLY_SUBDOMAINS}
      STAGING: ${SWAG_STAGING}
      EMAIL: ${ADMIN_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./swag/config:/config
    restart: unless-stopped
    logging: *default-logging
    networks:
      - swag_net
      - revproxy_apps

  keycloak-postgresql:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}_keycloak-postgresql
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging
    networks:
      - revproxy_apps

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_keycloak
    command:
      - start
      - --http-enabled=true
      - --proxy-headers=xforwarded
      - --hostname=${KEYCLOAK_HOSTNAME}
      - --hostname-strict=true
      - --metrics-enabled=true
      - --health-enabled=true
    depends_on:
      keycloak-postgresql:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgresql:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    restart: unless-stopped
    expose:
      - "8080"
      - "8443"
      - "9000"
    logging: *default-logging
    networks:
      - revproxy_apps

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_oauth2-proxy
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://auth.${BASE_DOMAIN}/realms/elasticlabs
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_REDIRECT_URL: https://admin.${BASE_DOMAIN}/oauth2/callback
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_UPSTREAMS: static://202
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_COOKIE_DOMAINS: .${BASE_DOMAIN}
      OAUTH2_PROXY_WHITELIST_DOMAINS: .${BASE_DOMAIN}
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SCOPE: "openid profile email"
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
    restart: unless-stopped
    expose:
      - "4180"
    logging: *default-logging
    networks:
      - revproxy_apps

  homer:
    image: b4bz/homer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_homer
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - ./homer:/www/assets/config:ro
    logging: *default-logging
    networks:
      - revproxy_apps

  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    command:
      - --base-url
      - /portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    expose:
      - "9000"
      - "9443"
    logging: *default-logging
    networks:
      - revproxy_apps

  #
  # Grafana and related services
  grafana:
    image: grafana/grafana:latest
    container_name: ${COMPOSE_PROJECT_NAME}_grafana
    environment:
      GF_SERVER_ROOT_URL: https://admin.${BASE_DOMAIN}/grafana/
      GF_SERVER_DOMAIN: admin.${BASE_DOMAIN}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: 
        grafana-piechart-panel,
        grafana-clock-panel,
        grafana-worldmap-panel,
        grafana-lokiexplore-app,
        grafana-polystat-panel,
        camptocamp-prometheus-alertmanager-datasource,
        vonage-status-panel
    volumes:
      - ./grafana/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    expose:
      - "3000"
    logging: *default-logging
    networks:
      - revproxy_apps

  loki:
    image: grafana/loki:2.9.0
    container_name: ${COMPOSE_PROJECT_NAME}_loki
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - loki_data:/loki
      - ./grafana/loki/config/loki-config.yml:/etc/loki/loki-config.yml:ro
    restart: unless-stopped
    expose:
      - "3100"
    logging: *default-logging
    networks:
      - revproxy_apps

  prometheus:
    image: prom/prometheus:latest
    container_name: ${COMPOSE_PROJECT_NAME}_prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.external-url=/prometheus/
      - --web.route-prefix=/
      - '--storage.tsdb.retention.time=7d'      # Adjust retention period
      - '--storage.tsdb.wal-compression'        # Compress write-ahead log
      - '--storage.tsdb.retention.size=10GB'    # Limit total storage size
      - '--web.enable-lifecycle'   
    volumes:
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./grafana/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    expose:
      - "9090"
    logging: *default-logging
    networks:
      - revproxy_apps

  alloy:
    image: grafana/alloy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./grafana/alloy/config.alloy:/etc/alloy/config.alloy:ro
    restart: unless-stopped
    expose:
      - "12345"
    logging: *default-logging
    networks:
      - revproxy_apps

  tempo:
    image: grafana/tempo:2.9.0
    container_name: ${COMPOSE_PROJECT_NAME}_tempo
    command:
      - -config.file=/etc/tempo/tempo-config.yaml
    volumes:
      - tempo_data:/var/tempo
      - ./grafana/tempo/tempo-config.yaml:/etc/tempo/tempo-config.yaml:ro
    restart: unless-stopped
    expose:
      - "3200"
      - "4317"
      - "4318"
    logging: *default-logging
    networks:
      - revproxy_apps
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME}_node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/textfile'
    pid: 'host'
    volumes:
      - /:/host:ro,rslave
      - ./grafana/node-exporter/textfile:/textfile:ro
    restart: unless-stopped
    expose:
      - "9100"
    logging: *default-logging
    networks:
      - revproxy_apps

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ${COMPOSE_PROJECT_NAME}_cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    command:
      - -url_base_prefix=/cadvisor
      - -housekeeping_interval=30s
      - -max_housekeeping_interval=35s
      - -event_storage_event_limit=default=0
      - -event_storage_age_limit=default=0
      - -disable_metrics=percpu,sched,tcp,udp,referenced_memory
      - -docker_only=true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    restart: unless-stopped
    expose:
      - "8080"
    logging: *default-logging
    networks:
      - revproxy_apps

  alertmanager:
    image: prom/alertmanager:latest
    container_name: ${COMPOSE_PROJECT_NAME}_alertmanager
    volumes:
      - ./grafana/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://admin.${BASE_DOMAIN}/alertmanager/'
      - '--web.route-prefix=/'
    expose:
      - "9093"
    restart: unless-stopped
    logging: *default-logging
    networks:
      - revproxy_apps

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: ${COMPOSE_PROJECT_NAME}_filebrowser
    environment:
      PUID: $(id -u)
      PGID: $(id -g)
      FILEBROWSER_ROOT: /srv
    command: >
      --database /database/filebrowser.db
      --root /srv
      --baseurl /data
      --address 0.0.0.0
      --port 80
      --log stdout
    volumes:
      - keycloak_postgres_data:/srv/keycloak-postgres:ro
      - portainer_data:/srv/portainer:ro
      - grafana_data:/srv/grafana
      - loki_data:/srv/loki
      - prometheus_data:/srv/prometheus
      - tempo_data:/srv/tempo
      - ./swag/config:/srv/swag
      - filebrowser_database:/database
      - filebrowser_config:/config
    restart: unless-stopped
    expose:
      - "80"
    logging: *default-logging
    networks:
      - revproxy_apps

networks:
  swag_net:
    external: true
    name: ${SWAG_NETWORK}
  revproxy_apps:
    external: true
    name: ${REVPROXY_APPS_NETWORK}

volumes:
  keycloak_postgres_data:
  portainer_data:
  grafana_data:
  loki_data:
  prometheus_data:
  tempo_data:
  filebrowser_database:
  filebrowser_config:
