location /oauth2/ {
    set $upstream http://oauth2-proxy/;
    proxy_pass http://$upstream:4180/;
    #include /config/nginx/snippets/proxy-common.conf;
}

location = /oauth2/auth {
    set $upstream oauth2-proxy;
    proxy_pass http://$upstream:4180/oauth2/auth;
    #include /config/nginx/snippets/proxy-common.conf;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
}
