services:
  postgresql:
    image: postgres:16
    container_name: authentik-postgresql
    env_file:
      - ./env/postgres.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - revproxy_apps

  redis:
    image: redis:7-alpine
    container_name: authentik-redis
    restart: unless-stopped
    networks:
      - revproxy_apps

  server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    env_file:
      - ./env/server.env
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./data/media:/media
      - ./data/custom-templates:/templates
    restart: unless-stopped
    networks:
      - revproxy_apps

  worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    command: worker
    env_file:
      - ./env/worker.env
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./data/media:/media
      - ./data/certs:/certs
      - ./data/custom-templates:/templates
    restart: unless-stopped
    networks:
      - revproxy_apps

networks:
  revproxy_apps:
    external: true