services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    env_file:
      - .env
    volumes:
      - ./acquis:/etc/crowdsec/acquis.d
      - ./data:/var/lib/crowdsec/data
      - /var/log:/var/log:ro
    restart: unless-stopped
    networks:
      - revproxy_apps

networks:
  revproxy_apps:
    external: true