---
title: "Elasticlabs Admin"
subtitle: "tennisme-revproxy"
header: true
footer: false
columns: 3
connectivityCheck: false

services:
  - name: "Admin"
    icon: "fas fa-shield-alt"
    items:
      - name: "Keycloak"
        subtitle: "IAM / SSO"
        url: "https://auth.elasticlabs.co"
      - name: "Portainer"
        subtitle: "Docker Administration"
        url: "https://admin.elasticlabs.co/portainer/"
      - name: "Grafana"
        subtitle: "Observability"
        url: "https://admin.elasticlabs.co/grafana/"
      - name: "cAdvisor"
        subtitle: "Container metrics UI"
        url: "https://admin.elasticlabs.co/cadvisor/"
      - name: "Files"
        subtitle: "Named volumes browser"
        url: "https://admin.elasticlabs.co/data /"
