server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name admin.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/snippets/security-headers.conf;
    include /config/nginx/snippets/oauth2-proxy.conf;

    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in;

    location = / {
        proxy_pass http://homepage:3000/;
        include /config/nginx/snippets/proxy-common.conf;
    }

    location /portainer/ {
        proxy_pass http://portainer:9000/;
        include /config/nginx/snippets/proxy-common.conf;
    }

    location /observe/ {
        proxy_pass http://openobserve:5080/observe/;
        include /config/nginx/snippets/proxy-common.conf;
    }
}
