server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name admin.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/snippets/security-headers.conf;
    include /config/nginx/snippets/oauth2-proxy.conf;

    #
    # At first leave commented, we need to configure oauth2-proxy and Keycloadk before enabling this
    # auth_request /oauth2/auth;
    # error_page 401 = /oauth2/sign_in;

    location = / {
        set $upstream homer;
        proxy_pass http://$upstream:8080/;
        #include /config/nginx/snippets/proxy-common.conf;
    }

    location /portainer/ {
        set $upstream portainer;
        proxy_pass http://$upstream:9000/;
        #include /config/nginx/snippets/proxy-common.conf;
    }

    location /grafana/ {
        set $upstream grafana;
        proxy_pass http://$upstream:3000/;
        #include /config/nginx/snippets/proxy-common.conf;
    }

    location /cadvisor/ {
        set $upstream cadvisor;
        proxy_pass http://$upstream:8080/;
        #include /config/nginx/snippets/proxy-common.conf;
    }

    location /files/ {
        set $upstream files;
        proxy_pass http://$upstream:80/ ;
        #include /config/nginx/snippets/proxy-common.conf;
    }
}
