server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name auth.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/snippets/security-headers.conf;

    client_max_body_size 20m;

    location / {
        proxy_pass http://authentik-server:9000;
        include /config/nginx/snippets/proxy-common.conf;
    }
}