location = /alertmanager {
    return 301 /alertmanager/;
}

location ^~ /alertmanager/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    auth_basic "Restricted";
    auth_basic_user_file /config/nginx/.htpasswd;

    proxy_pass http://alertmanager:9093/;
}