location = /alertmanager {
    return 301 /alertmanager/;
}

location ^~ /alertmanager/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    proxy_pass http://alertmanager:9093/;
}