location = /cadvisor {
    return 301 /cadvisor/;
}

location ^~ /cadvisor/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    auth_basic "Restricted";
    auth_basic_user_file /config/nginx/.htpasswd;

    proxy_pass http://cadvisor:8080;
}