## Version 2023/04/20
# make sure that your grafana container is named grafana
# make sure that grafana is set to work with the base url /grafana/
# grafana requires environment variables set thus:
#    environment:
#      - "GF_SERVER_ROOT_URL=https://my.domain.com/grafana"
#      - "GF_SERVER_DOMAIN=https://my.domain.com/"

location /prometheus/ {
    proxy_pass http://prometheus:9090/;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}