server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name admin.*;

    include /config/nginx/ssl.conf;

    location = / {
        return 302 /portainer/;
    }

    location /portainer/ {
        proxy_pass http://portainer:9000/;
        include /config/nginx/snippets/proxy-common.conf;
    }

    location /observe/ {
        proxy_pass http://openobserve:5080/observe/;
        include /config/nginx/snippets/proxy-common.conf;
    }
}