services:
  restic:
    image: restic/restic:latest
    container_name: restic
    env_file:
      - .env
    volumes:
      - ../../:/workspace:ro
      - ./repo:/repo
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]