- Infrastructure:
    - Keycloak:
        href: https://auth.elasticlabs.co
        description: IAM / SSO
    - Homepage:
        href: https://admin.elasticlabs.co
        description: Portail admin
    - Portainer:
        href: https://admin.elasticlabs.co/portainer/
        description: Administration Docker
    - OpenObserve:
        href: https://admin.elasticlabs.co/observe/
        description: Logs et observabilité
    - CrowdSec Console:
        href: https://app.crowdsec.net/
        description: Supervision CrowdSec
